In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("Finance_1.csv")

In [3]:
import os
os.listdir()

['.ipynb_checkpoints',
 'Banking_Data_Cleaning.ipynb',
 'Finance_1.csv',
 'Finance_2.xlsx',
 'Prinstine_Banking_Loan_Data.csv']

In [4]:
df2 = pd.read_excel("Finance_2.xlsx")

In [5]:
df2.head()

,id,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,...,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d
0,54734,0,1994-02-01,0,NaN,NaN,10,0,28854,0.521,...,21817.65,25000.00,4330.36,0.0,0.0,0.0,2011-10-01,7392.08,NaT,2012-08-01
1,55742,0,2000-10-01,0,NaN,NaN,7,0,33623,0.767,...,684.94,7000.00,1215.54,0.0,0.0,0.0,2011-06-01,228.48,NaT,2012-08-01
2,57245,0,1985-01-01,0,64.0,NaN,5,0,2584,0.404,...,1457.82,1200.00,257.82,0.0,0.0,0.0,2013-03-01,42.73,NaT,2016-05-01
3,57416,0,1996-12-01,1,58.0,NaN,14,0,3511,0.256,...,13073.71,10800.00,2407.76,0.0,0.0,0.0,2012-11-01,398.00,NaT,2016-05-01
4,58915,0,2000-11-01,1,NaN,NaN,3,0,33667,0.732,...,571.30,5024.99,818.88,0.0,0.0,0.0,2011-04-01,162.63,NaT,2014-03-01

In [6]:
print("Finance 1 Columns:\n", df1.columns.tolist(), "\n")
print("Finance 2 Columns:\n", df2.columns.tolist())

Finance 1 Columns:
 ['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti']

Finance 2 Columns:
 ['id', 'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d']

In [7]:
print("--- FINANCE 1 INFO ---")
df1.info()
print("\n--- FINANCE 2 INFO ---")
df2.info()

--- FINANCE 1 INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   39717 non-null  int64
 1   member_id            39717 non-null  int64
 2   loan_amnt            39717 non-null  int64
 3   funded_amnt          39717 non-null  int64
 4   funded_amnt_inv      39717 non-null  float64
 5   term                 39717 non-null  object
 6   int_rate             39717 non-null  object
 7   installment          39717 non-null  float64
 8   grade                39717 non-null  object
 9   sub_grade            39717 non-null  object
 10  emp_title            37258 non-null  object
 11  emp_length           38642 non-null  object
 12  home_ownership       39717 non-null  object
 13  annual_inc           39717 non-null  float64
 14  verification_status  39717 non-null  object
 15  issue_d              39717 non-null  object
 16  loan_status          39717 non-null  object
 17  pymnt_plan           39717 non-null  object
 18  desc                 26775 non-null  object
 19  purpose              39717 non-null  object
 20  title                39706 non-null  object
 21  zip_code             39717 non-null  object
 22  addr_state           39717 non-null  object
 23  dti                  39717 non-null  float64
dtypes: float64(4), int64(4), object(16)
memory usage: 7.3+ MB

--- FINANCE 2 INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       39717 non-null  int64
 1   delinq_2yrs              39717 non-null  int64
 2   earliest_cr_line         39717 non-null  datetime64[ns]
 3   inq_last_6mths           39717 non-null  int64
 4   mths_since_last_delinq   14035 non-null  float64
 5   mths_since_last_record   2786 non-null   float64
 6   open_acc                 39717 non-null  int64
 7   pub_rec                  39717 non-null  int64
 8   revol_bal                39717 non-null  int64
 9   revol_util               39667 non-null  float64
 10  total_acc                39717 non-null  int64
 11  initial_list_status      39717 non-null  object
 12  out_prncp                39717 non-null  float64
 13  out_prncp_inv            39717 non-null  float64
 14  total_pymnt              39717 non-null  float64
 15  total_pymnt_inv          39717 non-null  float64
 16  total_rec_prncp          39717 non-null  float64
 17  total_rec_int            39717 non-null  float64
 18  total_rec_late_fee       39717 non-null  float64
 19  recoveries               39717 non-null  float64
 20  collection_recovery_fee  39717 non-null  float64
 21  last_pymnt_d             39646 non-null  datetime64[ns]
 22  last_pymnt_amnt          39717 non-null  float64
 23  next_pymnt_d             1140 non-null   datetime64[ns]
 24  last_credit_pull_d       39715 non-null  datetime64[ns]
dtypes: datetime64[ns](4), float64(13), int64(7), object(1)
memory usage: 7.6+ MB

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   39717 non-null  int64
 1   member_id            39717 non-null  int64
 2   loan_amnt            39717 non-null  int64
 3   funded_amnt          39717 non-null  int64
 4   funded_amnt_inv      39717 non-null  float64
 5   term                 39717 non-null  object
 6   int_rate             39717 non-null  object
 7   installment          39717 non-null  float64
 8   grade                39717 non-null  object
 9   sub_grade            39717 non-null  object
 10  emp_title            37258 non-null  object
 11  emp_length           38642 non-null  object
 12  home_ownership       39717 non-null  object
 13  annual_inc           39717 non-null  float64
 14  verification_status  39717 non-null  object
 15  issue_d              39717 non-null  object
 16  loan_status          39717 non-null  object
 17  pymnt_plan           39717 non-null  object
 18  desc                 26775 non-null  object
 19  purpose              39717 non-null  object
 20  title                39706 non-null  object
 21  zip_code             39717 non-null  object
 22  addr_state           39717 non-null  object
 23  dti                  39717 non-null  float64
dtypes: float64(4), int64(4), object(16)
memory usage: 7.3+ MB

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       39717 non-null  int64
 1   delinq_2yrs              39717 non-null  int64
 2   earliest_cr_line         39717 non-null  datetime64[ns]
 3   inq_last_6mths           39717 non-null  int64
 4   mths_since_last_delinq   14035 non-null  float64
 5   mths_since_last_record   2786 non-null   float64
 6   open_acc                 39717 non-null  int64
 7   pub_rec                  39717 non-null  int64
 8   revol_bal                39717 non-null  int64
 9   revol_util               39667 non-null  float64
 10  total_acc                39717 non-null  int64
 11  initial_list_status      39717 non-null  object
 12  out_prncp                39717 non-null  float64
 13  out_prncp_inv            39717 non-null  float64
 14  total_pymnt              39717 non-null  float64
 15  total_pymnt_inv          39717 non-null  float64
 16  total_rec_prncp          39717 non-null  float64
 17  total_rec_int            39717 non-null  float64
 18  total_rec_late_fee       39717 non-null  float64
 19  recoveries               39717 non-null  float64
 20  collection_recovery_fee  39717 non-null  float64
 21  last_pymnt_d             39646 non-null  datetime64[ns]
 22  last_pymnt_amnt          39717 non-null  float64
 23  next_pymnt_d             1140 non-null   datetime64[ns]
 24  last_credit_pull_d       39715 non-null  datetime64[ns]
dtypes: datetime64[ns](4), float64(13), int64(7), object(1)
memory usage: 7.6+ MB

In [10]:
# 1. Clean Interest Rate (which is inside df1)
df1['int_rate'] = df1['int_rate'].astype(str).str.replace('%', '', regex=False).astype(float)

# 2. Clean Revolving Utilization (which lives inside df2)
df2['revol_util'] = df2['revol_util'].astype(str).str.replace('%', '', regex=False).astype(float)

# 3. Verify both successfully changed to float numbers
print("df1 int_rate type:", df1['int_rate'].dtype)
print("df2 revol_util type:", df2['revol_util'].dtype)

df1 int_rate type: float64
df2 revol_util type: float64

In [11]:
# Loop through both datasets to clean 'emp_length' simultaneously
for df_name, df in [('Finance 1', df1), ('Finance 2', df2)]:
    if 'emp_length' in df.columns:
        # Convert to string and strip characters
        df['emp_length'] = df['emp_length'].astype(str)
        df['emp_length'] = df['emp_length'].str.replace('years', '', regex=False)
        df['emp_length'] = df['emp_length'].str.replace('year', '', regex=False)
        df['emp_length'] = df['emp_length'].str.replace('+', '', regex=False)
        df['emp_length'] = df['emp_length'].str.replace('< 1', '0', regex=False)
        df['emp_length'] = df['emp_length'].str.strip()
        
        # Convert to clean integers and handle missing data
        df['emp_length'] = pd.to_numeric(df['emp_length'], errors='coerce').fillna(0).astype(int)
        print(f"✔️ {df_name} 'emp_length' successfully cleaned! Type: {df['emp_length'].dtype}")

✔️ Finance 1 'emp_length' successfully cleaned! Type: int64

In [12]:
# 1. Clean issue_d inside Finance 1
if 'issue_d' in df1.columns:
    df1['issue_d'] = pd.to_datetime(df1['issue_d'], format='%b-%Y', errors='coerce')
    print("✔️ Finance 1 'issue_d' converted to true Date format!")

# 2. Clean last_pymnt_d inside Finance 2
if 'last_pymnt_d' in df2.columns:
    df2['last_pymnt_d'] = pd.to_datetime(df2['last_pymnt_d'], format='%b-%Y', errors='coerce')
    print("✔️ Finance 2 'last_pymnt_d' converted to true Date format!")

✔️ Finance 1 'issue_d' converted to true Date format!
✔️ Finance 2 'last_pymnt_d' converted to true Date format!

In [13]:
print("--- Missing Values in Finance 1 ---")
# Display only columns that have at least one missing value
print(df1.isnull().sum()[df1.isnull().sum() > 0])

print("\n--- Missing Values in Finance 2 ---")
print(df2.isnull().sum()[df2.isnull().sum() > 0])

--- Missing Values in Finance 1 ---
emp_title     2459
issue_d      39717
desc         12942
title           11
dtype: int64

--- Missing Values in Finance 2 ---
mths_since_last_delinq    25682
mths_since_last_record    36931
revol_util                   50
last_pymnt_d                 71
next_pymnt_d              38577
last_credit_pull_d            2
dtype: int64

In [14]:
# 1. Clean Finance 1 Missing Values
if 'title' in df1.columns:
    df1['title'] = df1['title'].fillna('Unknown')

# 2. Clean Finance 2 Missing Values
# If there are any missing rows in revolving utilization or dates, handle them safely
if 'revol_util' in df2.columns:
    df2['revol_util'] = df2['revol_util'].fillna(0.0)

if 'last_pymnt_d' in df2.columns:
    # For missing dates, we fill with a placeholder date or leave as NaT (Not a Time)
    # Leaving as NaT is standard for dates so it doesn't skew time calculations
    pass 

# 3. Double-check to ensure no major nulls remain in crucial columns
print("Finance 1 remaining nulls in title:", df1['title'].isnull().sum())
print("Finance 2 remaining nulls in revol_util:", df2['revol_util'].isnull().sum())

Finance 1 remaining nulls in title: 0
Finance 2 remaining nulls in revol_util: 0

In [15]:
# Check for duplicate IDs in both datasets
print("Duplicate IDs in Finance 1:", df1['id'].duplicated().sum())
print("Duplicate IDs in Finance 2:", df2['id'].duplicated().sum())

Duplicate IDs in Finance 1: 0
Duplicate IDs in Finance 2: 0

In [16]:
# Look for rows where Interest Received is mathematically impossible 
# (Greater than the total money actually paid back)
anomaly_condition = (df2['total_rec_int'] > df2['total_pymnt']) & (df2['total_pymnt'] > 0)
anomalies = df2[anomaly_condition]

print(f"Number of financially anomalous rows found: {len(anomalies)}")

Number of financially anomalous rows found: 0

In [17]:
# Look for rows where Interest Received is mathematically impossible 
# (Greater than the total money actually paid back)
anomaly_condition = (df2['total_rec_int'] > df2['total_pymnt']) & (df2['total_pymnt'] > 0)
anomalies = df2[anomaly_condition]

print(f"Number of financially anomalous rows found: {len(anomalies)}")

Number of financially anomalous rows found: 0

In [18]:
# 1. Merge df1 and df2 horizontally using the unique 'id' column
master_df = pd.merge(df1, df2, on='id', how='inner')

# 2. Check the final dimensions of your unified dataset
print("--- MERGE SUCCESSFUL ---")
print("Master Dataset Shape (Rows, Columns):", master_df.shape)

# 3. View a quick breakdown of the combined columns
print("\nFirst 3 rows of the unified master dataset:")
master_df.head(3)

--- MERGE SUCCESSFUL ---
Master Dataset Shape (Rows, Columns): (39717, 48)

First 3 rows of the unified master dataset:

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d
0,54734,80364,25000,25000,19080.057200,36 months,11.89,829.10,B,B4,...,21817.65,25000.0,4330.36,0.0,0.0,0.0,2011-10-01,7392.08,NaT,2012-08-01
1,55742,114426,7000,7000,672.803839,36 months,10.71,228.22,B,B5,...,684.94,7000.0,1215.54,0.0,0.0,0.0,2011-06-01,228.48,NaT,2012-08-01
2,57245,138150,1200,1200,1200.000000,36 months,13.11,40.50,C,C2,...,1457.82,1200.0,257.82,0.0,0.0,0.0,2013-03-01,42.73,NaT,2016-05-01

In [19]:
# Export the unified master dataset to a clean CSV file
master_df.to_csv('Prinstine_Banking_Loan_Data.csv', index=False)

print("🎉 Success! Your clean master dataset has been exported as 'Prinstine_Banking_Loan_Data.csv'!")
print("Look in your current Jupyter folder—the file is sitting there ready for action!")

🎉 Success! Your clean master dataset has been exported as 'Prinstine_Banking_Loan_Data.csv'!
Look in your current Jupyter folder—the file is sitting there ready for action!